### PR TITLE
chore: `__builtin_popcount` to replace BitCount8

### LINKED ISSUE #308: Use popcount intrinsics in `exorBits.cpp`
`exorBits.cpp` uses a `BitCount` table to compute popcount. Other parts of abc use `__builtin_popcount`, and every modern CPU supports popcount in hardware, so we might as well use it in `exorBits` too.

### PR DESCRIPTION
**Pull request by coastalwhite**
This replaces all occurrences of the `BitCount8` static array with the `__builtin_popcount`. It is a rather simple and small PR.

Fixes #308.

### CODE REVIEW

**Comment by alanminko** [comment]
Unfortunately there is a problem with the Windows build:
D:\a\abc\abc\src\misc\util\utilTruth.h(132,54): error C3861: '__builtin_popcount': identifier not found [D:\a\abc\abc\abclib.vcxproj]

**Comment by coastalwhite** [comment]
I can use the `__popcnt` built-in on MSVC. Will update later today.

**Comment by coastalwhite** [comment]
I have added the `__builtin_popcount` intrinsic for MSVC.

**Comment by alanminko** [comment]
Thank you for the change set!

**Pull request merged**
